#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=00:20:00   # walltime
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks=1      # limit to one node
#SBATCH --cpus-per-task=1  # number of processor cores (i.e. threads)
#SBATCH --partition=haswell,sandy,west
#SBATCH --mem-per-cpu=2000M   # memory per CPU core
#SBATCH -J "Validation_Subsampling"   # job name
#SBATCH --mail-user=julien.fischer@mailbox.tu-dresden.de   # email address
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH -A p_da_rgb


# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
OUTFILE="validation_subsampling.txt"
/scratch/ws/fahe458b-p_da_rgb-depth_estimation_CNN/Validation_Subsampling.py -f /scratch/ws/fahe458b-p_da_rgb-depth_estimation_CNN/data/val_old -o /scratch/ws/fahe458b-p_da_rgb-depth_estimation_CNN/data/validation > "$OUTFILE"

exit 0

