#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=20:00:00   # walltime
#SBATCH --nodes=1   # number of nodes
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1      # limit to one node
#SBATCH --cpus-per-task=4  # number of processor cores (i.e. threads)
#SBATCH --partition=ml
#SBATCH --mem-per-cpu=4000M   # memory per CPU core
#SBATCH -J "Training_1"   # job name
#SBATCH --mail-user=julien.fischer@mailbox.tu-dresden.de   # email address
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH -A p_da_rgb


# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
OUTFILE="training_output.txt"

module load modenv/ml
module load TensorFlow/1.14.0-Anaconda-3.6
python /scratch/ws/fahe458b-p_da_rgb-depth_estimation_CNN/Model.py  > "$OUTFILE"

exit 0